//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : �����������ϵͳ
//  @ File Name : Generate.java
//  @ Date : 2013/5/1
//  @ Author : 
//
//



package net.codegenerate;

import java.sql.SQLException;


public interface GenerateCode {
	public void generateCode() throws SQLException, InstantiationException, IllegalAccessException, ClassNotFoundException;
}
