//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : �����������ϵͳ
//  @ File Name : Generator.java
//  @ Date : 2013/5/1
//  @ Author : 
//
//

package net.codegenerate;

import java.util.HashMap;
import java.util.Map;

public class Generator {
	private static Map<String, String> parameters = null;

	/**
	 * 获取参数
	 * 
	 * @return
	 */
	public static Map<String, String> getParam() {
		if (parameters == null) {
			parameters = new HashMap<String, String>();
		}
		return parameters;
	}
}
